export const text = {
  display01: {
    fontFamily: "Pretendard",
    fontSize: "96px",
    letterSpacing: "-3%",
    lineHeight: "120%",
    fontWeight: 600,
  },
  title01: {
    fontFamily: "Pretendard",
    fontSize: "36px",
    letterSpacing: "-2%",
    lineHeight: "140%",
    fontWeight: 700,
  },
  title02: {
    fontFamily: "Pretendard",
    fontSize: "32px",
    letterSpacing: "-2%",
    lineHeight: "140%",
    fontWeight: 700,
  },
  title03: {
    fontFamily: "Pretendard",
    fontSize: "28px",
    letterSpacing: "-2%",
    lineHeight: "140%",
    fontWeight: 700,
  },
  headline01: {
    fontFamily: "Pretendard",
    fontSize: "20px",
    letterSpacing: "-2%",
    lineHeight: "140%",
    fontWeight: 600,
  },
  headline02: {
    fontWeight: 500,
    fontFamily: "Pretendard",
    fontSize: "20px",
    letterSpacing: "-2%",
    lineHeight: "140%",
  },
  headline03: {
    fontWeight: 600,
    fontFamily: "Pretendard",
    fontSize: "16px",
    letterSpacing: "-2%",
    lineHeight: "140%",
  },
  headline04: {
    fontWeight: 500,
    fontFamily: "Pretendard",
    fontSize: "16px",
    letterSpacing: "-2%",
    lineHeight: "140%",
  },
  body01: {
    fontFamily: "Pretendard",
    fontSize: "14px",
    letterSpacing: "0%",
    lineHeight: "160%",
    fontWeight: 600,
  },
  body02: {
    fontFamily: "Pretendard",
    fontSize: "14px",
    letterSpacing: "0%",
    lineHeight: "160%",
    fontWeight: 500,
  },
  label01: {
    fontFamily: "Pretendard",
    fontSize: "15px",
    letterSpacing: "0%",
    lineHeight: "140%",
    fontWeight: 600,
  },
  label02: {
    fontFamily: "Pretendard",
    fontSize: "15px",
    letterSpacing: "0%",
    lineHeight: "140%",
    fontWeight: 500,
  },
  label03: {
    fontFamily: "Pretendard",
    fontSize: "14px",
    letterSpacing: "0%",
    lineHeight: "140%",
    fontWeight: 600,
  },
  label04: {
    fontFamily: "Pretendard",
    fontSize: "14px",
    letterSpacing: "0%",
    lineHeight: "140%",
    fontWeight: 500,
  },
  label05: {
    fontFamily: "Pretendard",
    fontSize: "12px",
    letterSpacing: "0%",
    lineHeight: "140%",
    fontWeight: 600,
  },
  label06: {
    fontFamily: "Pretendard",
    fontSize: "12px",
    letterSpacing: "0%",
    lineHeight: "140%",
    fontWeight: 500,
  },
  label07: {
    fontFamily: "Pretendard",
    fontSize: "10px",
    letterSpacing: "0%",
    lineHeight: "140%",
    fontWeight: 600,
  },
  label08: {
    fontFamily: "Pretendard",
    fontSize: "10px",
    letterSpacing: "0%",
    lineHeight: "140%",
    fontWeight: 500,
  },
  label09: {
    fontFamily: "Pretendard",
    fontSize: "15px",
    letterSpacing: "0%",
    lineHeight: "140%",
    fontWeight: 500,
  },
  label10: {
    fontFamily: "Pretendard",
    fontSize: "10px",
    letterSpacing: "0%",
    lineHeight: "140%",
    fontWeight: 600,
  },
};
